name: Test

on:
  workflow_dispatch:
      
jobs:
  test-inbuild-runner-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-world
        run: echo "Hello World!"
        
      - name: java-version
        run: java --version
      
      - name: maven-version
        run: mvn --version
        
      - name: python-version
        run: python --version
        
  test-tf-version:
    runs-on: ubuntu-latest
    steps:
      - name: tf-version
        run: terraform --version
      
